image: ghcr.io/cirruslabs/flutter:latest
stages:
  - build
  - deploy

before_script:
  - flutter clean
  - flutter pub get
  - flutter pub upgrade

pages:
  stage: deploy
  script:
    - flutter build web --release --base-href /testman/
    - cp -r build/web public
  artifacts:
    untracked: false
    when: on_success
    paths:
      - public
  only:
    - master

android:
  stage: deploy
  script:
    - flutter build apk --release --obfuscate --split-per-abi --split-debug-info .debug
  artifacts:
    untracked: false
    when: on_success
    paths:
      - build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
      - build/app/outputs/flutter-apk/app-x86_64-release.apk
  only:
    - master
